spring:
  profiles:
    active:
      - dev
---
server:
  port: 3355
spring:
  application:
    name: MICRO-SERVER-DEV
  profiles: dev #开发环境
---
server:
  port: 3356
spring:
  application:
    name: MICRO-SERVER-TEST
  profiles: test #测试环境
————————————————
版权声明：本文为CSDN博主「龙王啊」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/qq_44575680/article/details/106784855
